name: ci
on:
  push:
  pull_request:
jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.25', '1.26']
        redis: ['redis:6.2-alpine', 'redis:7-alpine']
    services:
      redis:
        image: ${{ matrix.redis }}
        ports:
          - 6379:6379
    env:
      CONVREDIS_TEST_ADDR: localhost:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: make check
